version: "2.1"
services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - 8080:80
    # 指定了容器是否运行在特权模式下。在这里，设置为 true，表示容器拥有主机的一些特权
    privileged: true
